version: '3.6'

services: 
    some-rabbit:
        image: rabbitmq:3-management
        container_name: some-rabbit
        ports: 
            - 4369:4369
            - 5671:5671
            - 5672:5672
            - 15671:15671
            - 15672:15672
            - 25672:25672
        networks: 
            - qualifacts_net
networks: 
    qualifacts_net:
        #driver: bridge
        external: true