server:
  port: 3000
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .jsp
  rabbitmq:
    host:  localhost
    username: guest
    password: guest
    port: 5672

service:
  core:
    vacuna:
      url: http://localhost:8080/api/vacuna
      queue:
        citas:
          rabbitmq: 
            queue: citas.queue
            exchange: citas.exchange
            routingkey: citas.routingkey
